### PR TITLE
Updated to support Apple Sillicon

### PR DESCRIPTION
**Pull request by vitorgalvao**
This is your own code from https://github.com/xilopaint/alfred-about-this-mac/issues/3#issuecomment-781948459 plus @ChristoferK’s [updated AppleScript](https://github.com/xilopaint/alfred-about-this-mac/issues/3#issuecomment-842060489) and a small version bump.

Worth nothing the CPU icon says “Intel” which might confuse some users. Maybe the source where you got this one has an alternative for ARM, or something without anything written?

### CODE REVIEW

**Comment by xilopaint** [comment]
Could you post a screenshot of the Alfred bar after invoking the keyword?

**Comment by vitorgalvao** [comment]
Before the change:



After:

**Comment by xilopaint** [comment]
Hey @vitorgalvao, maybe you can help me with a question. I got a new Mac a few days ago (MPB M2) and used the Migration Assistant for the initial setup. It imported my user account from my old Intel MBA. The problem is that the `com.apple.SystemProfiler.plist` didn't regenerate, so this workflow showed my old Mac's name and model — the remaining information is correctly displayed by the workflow and I have no issues with About This Mac UI on macOS. Maybe the issue is related to [this thread](https://forums.macrumors.com/threads/how-to-find-out-model-year-with-terminal.2352765/). I tried moving `com.apple.SystemProfiler.plist` from its original folder to see if the file could be regenerated and it was, but with no mention of the machine model name.

This is how the workflow shows the information currently:

Screen Shot 2022-10-14 at 08 21 57

Do you have a clue on how to fix this?

**Comment by vitorgalvao** [comment]
I’d try using an alternative approach, such as the `system_profiler SPHardwareDataType` command mentioned in the thread.

**Comment by xilopaint** [comment]
> I’d try using an alternative approach, such as the `system_profiler SPHardwareDataType` command mentioned in the thread.

Yes, I'm already working on it. It's a better approach. But I still want to fix my `com.apple.SystemProfiler.plist` file which seems broken on my machine. 😔

**Comment by vitorgalvao** [comment]
Closing due to the new release.

> But I still want to fix my `com.apple.SystemProfiler.plist` file which seems broken on my machine.

Not something I’d worry about. Others report the same thing in the thread. If it’s copied with Migration Assistant and can have wrong information, either it’s a bug or Apple doesn’t rely on it anyway. It may exist for legacy reasons.

**Pull request closed without merging**
