### PR TITLE
Fix inconsistency in mod keys

### PR DESCRIPTION
**Pull request by Acidham**
The workflow was not able to open the web browser. I found some inconsistencies in mod keys where the text was arg value instead of the URL.

### CODE REVIEW

**Comment by xilopaint** [comment]
Looks good. Could you keep `cmd` mod key for the `Copy to Clipboard` action? In your implementation people may not notice that actioning the item is enough to do the job.

**Comment by Acidham** [comment]
I was not sure because arg was set to text instead of URL and this caused the error. The only valid default action would be copy to clipboard and the other two mods seems to be the Browser action. Or do I miss something?

**Comment by xilopaint** [comment]
> I was not sure because arg was set to text instead of URL and this caused the error.

It's likely a mistake I committed when adapted [the original workflow](https://www.alfredforum.com/topic/2025-about-this-mac/). Your PR is good in fixing it.

> The only valid default action would be copy to clipboard and the other two mods seems to be the Browser action. 

I prefer not using a default action since the subtitle does not inform the user that actioning the item will copy the text to clipboard. So I prefer to use `cmd` to `Copy to Clipboard`, `alt` to `Open Apple Specifications Site for This Hardware` and `ctrl` to `Open Apple Support Site for This Hardware`.

Could you make these changes in your PR so I can merge it?

**Comment by Acidham** [comment]
Sure can do but tell me what should happen when pressing enter? Nothing? If yes I could implement valid:false 
Let me know an I will add

**Comment by xilopaint** [comment]
> Sure can do but tell me what should happen when pressing enter? Nothing? If yes I could implement valid:false
> Let me know an I will add

Well, my take on this may be not so "alfredish" but I don't particularly like valid:false as I can't dismiss the Alfred bar by actioning the return key even if it does nothing, which is the case here.

**Pull request merged**
