### PR TITLE
Cache machine icon

### PR DESCRIPTION
**Pull request by vitorgalvao**
Required small tweaks to the AppleScript.

### CODE REVIEW

**Comment by xilopaint** [comment]
What happens if someone buys a new Mac and uses the Migration Assistant? Is there any possibility the cache folder is imported? I like the idea of caching the icon but I want to make sure that people will get accurate info if they change their Mac.

**Comment by vitorgalvao** [comment]
Caches are never meant to be transferred over, that would be a waste. They’re temporary data of a particular state.

**Comment by xilopaint** [comment]
Really? I came across [this post](https://discussions.apple.com/thread/252599080?answerId=254907613022#254907613022) from Apple Support Community that mentions caches.

**Comment by vitorgalvao** [comment]
It mentions caches in the context of “Other” in disk usage, not “Other” in Migration Assistant. Those are different things. That page mentions temporary files as well, which wouldn’t make sense to copy over either. Caches are the same, they can always be rebuilt with fresh data (that’s their point), copying older stuff would be wasteful.

It’s a known trick to clear the iOS “Other” storage to backup up everything and then restore. “Other”, which contains accumulated caches, logs, and other temporary data, gets significantly smaller because what’s not necessary and can be regenerated does not get backed up.

If it concerns you to that point, add a `|| -n "$(find "${MACHINE_ICON}" -mtime +30)"` to the `if` and the icon will also be recreated if it’s older than 30 days.

**Comment by xilopaint** [comment]
> It mentions caches in the context of “Other” in disk usage, not “Other” in Migration Assistant.

Oh, you're right. That was not what I understood at first.

**Pull request merged**
